# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: AutoPkg

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant
    - name: Test
      run: |
        ls -l --block-size=m /tmp/Jmol.jar
        ls -l --block-size=m build/Jmol.jar
    - name: Publish jar
      uses: softprops/action-gh-release@v1
      with:
        tag_name: auto
        prerelease: false
        draft: false
        files: |
          /tmp/Jmol.jar
