# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: AutoPkg

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  TAG_NAME: "auto"
  SOFTWARE_NAME: "ldr-translate"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml

    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        prerelease: true
        draft: false
        files: |
          build/Jmol.jar
